color = {
    'white': '#FFFFFF',
    'silver': '#C0C0C0',
    'gray': '#808080',
    'black': '#000000',
    'red': '#FF0000',
    'orange': '#FFA500',
    'maroon': '#800000',
    'yellow': '#FFFF00',
    'olive': '#808000',
    'lime': '#00FF00',
    'green': '#008000',
    'aqua': '#00FFFF',
    'teal': '#008080',
    'blue': '#0000FF',
    'blue_vivid': '#0055FF',
    'navy': '#000080',
    'fuchsia': '#FF00FF',
    'purple': '#800080',
    'violet': '#EE82EE',
    'pink': '#FFAAE2',
    }

standard_templates = {
    's/r zone': {
        'Label': 'S/R Zone',
        'Text Color': color['white'], 'Line Color': color['purple'], 'Band Color': color['purple'],
        'Band Offset': 6,
        'Show Label': 'Y',
        'Show Price': 'Y',
        },
    'lvn': {
        'Label': 'LVN',
        'Text Color': color['white'], 'Line Color': color['blue_vivid'], 'Band Color': color['blue_vivid'],
        'Priority': -10,
        },
    'hva': {
        'Label': 'HVA',
        'Text Color': color['black'], 'Line Color': color['yellow'], 'Band Color': color['yellow'],
        'Priority': -15,
        },
    'stat': {
        'Label': 'Misc Stat',
        'Text Color': color['white'],
        'Line Color': color['olive'],
        'Band Color': color['olive'],
        'Band Offset': 1,
        'Priority': 10,
        },
    'vpoc': {
        'Label': 'VPOC',
        'Text Color': color['white'],
        'Line Color': color['orange'],
        'Band Color': color['orange'],
        'Band Offset': 0,
        },
    'poor extreme': {
        'Label': 'Poor Hi/Lo',
        'Text Color': color['white'],
        'Line Color': color['orange'],
        'Band Color': color['orange'],
        'Band Offset': 0,
        },
    'gap': {
        'Label': 'Gap',
        'Text Color': color['white'],
        'Line Color': color['green'],
        'Band Color': color['green'],
        'Priority': -12,
        },
    'single print': {
        'Label': 'Single Print',
        'Text Color': color['white'],
        'Line Color': color['pink'],
        'Band Color': color['pink'],
        'Priority': -8,
        },
    'technical': {
        'Label': 'Pivot',
        'Text Color': color['white'],
        'Line Color': color['red'],
        'Band Color': color['red'],
        'Band Offset': 1,
        },
    }
